### ISSUE TITLE
Always On synching doesn't always work in Glpyhs 2

### ISSUE THREAD

**Issue by weiweihuanghuang** [underscoretype/glyphs-plugin-sync-metrics-keys#12]
How exactly do you force it to activate? It doesn't always synch – I think it was better when I could call the plugin to activate..

**Comment by weiweihuanghuang** [comment]
Wait am I getting this confused with another plugin that would sync all metrics in a font

**Comment by weiweihuanghuang** [comment]
Ah my bad I was thinking of this
https://github.com/jayKayEss/MetricsSolver

**Comment by kontur** [comment]
No worries ;)
