### ISSUE TITLE
Syncing issue with nested components

### ISSUE THREAD

**Issue by gorjious** [underscoretype/glyphs-plugin-sync-metrics-keys#9]
Hello

I am running into an issue with the metric keys syncing to glyphs that have nested components. I don't think I've noticed the issue before because I may have been using automatic alignment. 

I am attaching a screen recording of an example. 
In the top line, the "զ" is comprised of two components (automatic alignment disabled). 
In the bottom line, there is an alternate "զ" which references the զ in the top line as a component (automatic alignment disabled).
The LSB of both զS are synced with օ.

When changing the LSB of օ the LSBs of both զs change, however, the issue is that RSB of the զ in the bottom line doesn't retain the original RSB as it does in the top line. 

I can counter this by locking in the RSB using "==30", however, it seems strange that it would behave differently from the top line. 

The example is from Glyphs 3 – 3.0.2 (3042) but I check in G2 and it is the same.

Sidenote: The plugin is incredibly helpful and I use it constantly. Thank you for making it! 

[sync_metric_keys_issue.mov.zip](https://github.com/underscoretype/glyphs-plugin-sync-metrics-keys/files/5668096/sync_metric_keys_issue.mov.zip)

**Comment by kontur** [comment]
Thanks for the detailed feedback and the video! I have myself noticed that dragging paths and components in glyphs with sidebearing keys is often not ideal. I will see if I can work on a general update to the plugin over the Christmas time ;)

**Comment by kontur** [comment]
I've just published an update to the plugin that should fix this. @gorjious After you have updated, could you test this same thing again and see if it still persists or if this is fixed now for you as well?

**Comment by gorjious** [comment]
All the issues seem to be fixed and things are working smoothly. 
Thank you, Johannes, I appreciate the update and the great plugin!
